// <auto-generated />
using System;
using LetsChat.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LetsChat.Infrastructure.Migrations
{
    [DbContext(typeof(LetsChatDbContext))]
    [Migration("20260921222422_AddPreKeys")]
    partial class AddPreKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LetsChat.Infrastructure.Persistence.AccountRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("LetsChat.Infrastructure.Persistence.ContactEdgeRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AddresseeAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("addressee_account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("RequesterAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_account_id");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("AddresseeAccountId");

                    b.HasIndex("RequesterAccountId", "AddresseeAccountId")
                        .IsUnique();

                    b.ToTable("contact_edges", (string)null);
                });

            modelBuilder.Entity("LetsChat.Infrastructure.Persistence.DeviceRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DeviceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("device_number");

                    b.Property<string>("IdentityKeyPublic")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identity_key_public");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique();

                    b.HasIndex("AccountId", "DeviceNumber")
                        .IsUnique();

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("LetsChat.Infrastructure.Persistence.OneTimePreKeyRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<int>("KeyId")
                        .HasColumnType("integer")
                        .HasColumnName("key_id");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("public_key");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("DeviceId", "KeyId")
                        .IsUnique();

                    b.ToTable("one_time_prekeys", (string)null);
                });

            modelBuilder.Entity("LetsChat.Infrastructure.Persistence.PendingEnvelopeRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at_ms");

                    b.Property<string>("RecipientAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipient_address");

                    b.Property<string>("SenderAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sender_address");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("RecipientAddress");

                    b.ToTable("pending_envelopes", (string)null);
                });

            modelBuilder.Entity("LetsChat.Infrastructure.Persistence.PqLastResortPreKeyRow", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("KeyId")
                        .HasColumnType("integer")
                        .HasColumnName("key_id");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("public_key");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("signature");

                    b.HasKey("DeviceId");

                    b.ToTable("pq_last_resort_prekeys", (string)null);
                });

            modelBuilder.Entity("LetsChat.Infrastructure.Persistence.RefreshTokenRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("LetsChat.Infrastructure.Persistence.SignedPreKeyRow", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("KeyId")
                        .HasColumnType("integer")
                        .HasColumnName("key_id");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("public_key");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("signature");

                    b.HasKey("DeviceId");

                    b.ToTable("signed_prekeys", (string)null);
                });

            modelBuilder.Entity("LetsChat.Infrastructure.Persistence.ContactEdgeRow", b =>
                {
                    b.HasOne("LetsChat.Infrastructure.Persistence.AccountRow", null)
                        .WithMany()
                        .HasForeignKey("AddresseeAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LetsChat.Infrastructure.Persistence.AccountRow", null)
                        .WithMany()
                        .HasForeignKey("RequesterAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LetsChat.Infrastructure.Persistence.DeviceRow", b =>
                {
                    b.HasOne("LetsChat.Infrastructure.Persistence.AccountRow", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LetsChat.Infrastructure.Persistence.OneTimePreKeyRow", b =>
                {
                    b.HasOne("LetsChat.Infrastructure.Persistence.DeviceRow", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LetsChat.Infrastructure.Persistence.PendingEnvelopeRow", b =>
                {
                    b.OwnsOne("LetsChat.Contracts.EncryptedEnvelope", "Envelope", b1 =>
                        {
                            b1.Property<string>("PendingEnvelopeRowId")
                                .HasColumnType("text");

                            b1.Property<string>("Ciphertext")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<long>("CreatedAt")
                                .HasColumnType("bigint");

                            b1.Property<string>("Header")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Id")
                                .HasColumnType("text");

                            b1.Property<string>("RecipientAddress")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("SenderAddress")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Version")
                                .HasColumnType("integer");

                            b1.HasKey("PendingEnvelopeRowId");

                            b1.ToTable("pending_envelopes");

                            b1.ToJson("payload");

                            b1.WithOwner()
                                .HasForeignKey("PendingEnvelopeRowId");
                        });

                    b.Navigation("Envelope")
                        .IsRequired();
                });

            modelBuilder.Entity("LetsChat.Infrastructure.Persistence.PqLastResortPreKeyRow", b =>
                {
                    b.HasOne("LetsChat.Infrastructure.Persistence.DeviceRow", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LetsChat.Infrastructure.Persistence.SignedPreKeyRow", b =>
                {
                    b.HasOne("LetsChat.Infrastructure.Persistence.DeviceRow", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
