// <auto-generated />
using System;
using LetsChat.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LetsChat.Infrastructure.Migrations
{
    [DbContext(typeof(LetsChatDbContext))]
    [Migration("20260920130619_AddAccounts")]
    partial class AddAccounts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LetsChat.Infrastructure.Persistence.AccountRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("LetsChat.Infrastructure.Persistence.PendingEnvelopeRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at_ms");

                    b.Property<string>("RecipientAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipient_address");

                    b.Property<string>("SenderAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sender_address");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("RecipientAddress");

                    b.ToTable("pending_envelopes", (string)null);
                });

            modelBuilder.Entity("LetsChat.Infrastructure.Persistence.PendingEnvelopeRow", b =>
                {
                    b.OwnsOne("LetsChat.Contracts.EncryptedEnvelope", "Envelope", b1 =>
                        {
                            b1.Property<string>("PendingEnvelopeRowId")
                                .HasColumnType("text");

                            b1.Property<string>("Ciphertext")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<long>("CreatedAt")
                                .HasColumnType("bigint");

                            b1.Property<string>("Header")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Id")
                                .HasColumnType("text");

                            b1.Property<string>("RecipientAddress")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("SenderAddress")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Version")
                                .HasColumnType("integer");

                            b1.HasKey("PendingEnvelopeRowId");

                            b1.ToTable("pending_envelopes");

                            b1.ToJson("payload");

                            b1.WithOwner()
                                .HasForeignKey("PendingEnvelopeRowId");
                        });

                    b.Navigation("Envelope")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
